name: pkg_onbording_slide
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/JL-Lucas-DVS/pkg_onbordign_slide/tree/main

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.18.0 <1.0.0" 
  freezed_annotation: ">=0.15.0 <1.0.0" 
  hooks_riverpod: ">=1.0.0 <2.0.0"  
  flutter_svg: ">=1.1.1 <2.0.0" 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <3.0.0"  
  lint: ">=1.0.0 <2.0.0"
  freezed: ">=0.15.0 <1.0.0" 
  build_runner: ">=2.0.6 <3.0.0"
  

flutter:
